### ISSUE TITLE
Request for Gemini Pro API Compatibility for stand alone functionally without Open AI

### ISSUE THREAD

**Issue by reconsumeralization** [eliranwong/letmedoit#52]
As a user of LetMeDoIt AI, I find the current features and capabilities incredibly useful. However, I believe that integrating support for the Google Gemini Pro API, independent of needing open ai,  would significantly enhance its functionality. The Gemini Pro API provides advanced language models and natural language understanding, which could greatly benefit LetMeDoIt AI.

Proposal: I kindly request that the LetMeDoIt AI development team consider creating a version that is compatible with the Google Gemini Pro API. This would allow users to seamlessly leverage the power of both LetMeDoIt AI and Gemini Pro for even more efficient and accurate interactions.

Benefits:

Enhanced Language Understanding: Gemini Pro’s advanced language models can improve context comprehension and generate more accurate responses.
Expanded Use Cases: Integration with Gemini Pro would open up new possibilities for LetMeDoIt AI, such as better code generation, improved content creation, and enhanced task automation.
Community Interest: Many users are excited about the potential of combining LetMeDoIt AI with Gemini Pro, making it a valuable addition to the LetMeDoIt ecosystem.
Steps:

Investigate the feasibility of integrating Gemini Pro into LetMeDoIt AI.
Update LetMeDoIt AI documentation and provide clear instructions for users on how to enable Gemini Pro support.
Additional Notes: I appreciate the hard work put into LetMeDoIt AI and believe that this enhancement would make it an even more powerful tool. Thank you for considering my request!

**Comment by eliranwong** [comment]
I share the same desire to have Gemini Pro API used as the main engine.  However, Google API is not up to the task yet.

I had high hope when Gemini Pro is launched, but have been disappointed so far due to its weakness in supporting function calling.

So far tested, Google Gemini function calling has the following limitations which makes it not useful as OpenAI ones:

* limited support of one single function call at a time whereas openai support multiple
* does not offer "auto" option when function call is used, so not yet smart enough to decide whether a mere chat / another function call is needed.

With that said, I want to support that, but just need to wait for Google to improve the Gemini function calling features first.  For now, it is way behind what OpenAI does with function calling.

**Comment by eliranwong** [comment]
Bty, please kindly notify me when Google improves Gemini function calling in case I miss that.

**Comment by reconsumeralization** [comment]
They have released official support for function calling.  ![Screenshot_20240224-195629.png](https://github.com/eliranwong/letmedoit/assets/73420525/96ef2070-e7ec-4013-8717-0ad6d03dfcb5)

![Screenshot_20240224-195608.png](https://github.com/eliranwong/letmedoit/assets/73420525/a891cb96-2faa-465c-80c9-c2db43ac8880)

**Comment by reconsumeralization** [comment]
I have been working on a Concept for natural language conversion from open AI to natural language to Gemini format also.

**Comment by eliranwong** [comment]
Thanks for your information.  I know and tested [[for example](https://github.com/eliranwong/letmedoit/blob/main/tests/geminipro_vision.py)] that Gemini Pro.  It works but not as sophisticated and smart as OpenAI. Did you try running multiple functions in one go with Google Gemini Pro?  I did, disappointed.  I also found that Google Gemini function calling is very stubborn that does not distinguish automatically between the needs of a mere chat or a function.  That's why put me away from using Google API as core engine previously.

However, I just come up a solution in the last two days that can move in the direction for users to choose between: numerous free & offline open-source LLMs, OpenAI, and Google Gemini API.

It would take time to rewrite a lot if I do it in LetMeDoIt AI project.  Instead, I will implement this in a separate project, FreeGenius.

https://github.com/eliranwong/freegenius

There some other users requested using Google Gemini / open-source LLMs, I think this project is the answer to your request and all those requests.

**Comment by eliranwong** [comment]
You may read: https://github.com/eliranwong/freegenius/blob/main/README.md#approach-to-run-function-calling-equivalent-features-offline-with-common-hardwares

**Comment by eliranwong** [comment]
Just an update.  Progress is good for supporting Google Gemini Pro in this sibling project: https://github.com/eliranwong/freegenius

**Comment by eliranwong** [comment]
I close this issue for now.  You may check FreeGenius AI if you are interested.  Thanks

**Comment by eliranwong** [comment]
Done, please check: https://github.com/eliranwong/freegenius
